file_format: "1"
id: corne
name: Corne
type: shield
url: https://github.com/EnormousDoggo/zmk-config-corne
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - corne_left
  - corne_right